version: '3.8'

volumes:
  db:
    driver: local

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
        
  webapi:
    privileged: true
    container_name: Tamagotchi.API
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - "80:80"
      - "443:443"
    build:
      dockerfile: ./Tamagotchi.API/Dockerfile
      context: ../
    depends_on:
      - db